# Generated by Django 3.2.7 on 2021-09-14 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_username_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='USERNAME_FIELD',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
