# Generated by Django 3.2.7 on 2021-09-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
